#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Create The Console Application
|--------------------------------------------------------------------------
|
|
*/

$app = require __DIR__ . '/bootstrap/app.php';

di()->get('console')->run();
